---
title: "Daily.Log"
author: "LMAS"
date: "`r format(Sys.Date(),format='%B %d, %Y')`"
output:  
  html_document
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
# {.tabset}
A compilation of hours spent on each LMAS project since the start of the quarantine.

##Tabulated Data {.tabset .tabset-fade}
```{r, echo=FALSE, results='asis', message=FALSE, warning=FALSE}
library(readxl)
library(tidyr)
library(dplyr)
library(tidyverse)
library(lubridate)
library(knitr)
library(DT)

#read in table types
alene<-read_excel("C:/Users/amonion.000/New York State Office of Information Technology Services/LMAS - General/telecommuting_journal_V2 (002)_AMO.xls",sheet="Work Journal",col_types = c("date", "text","text", "numeric", "numeric","text","text","text"))
alene<-as.data.frame(alene)
alene<-alene %>%
  # rename with first row
  set_names(c("DATE","Project","Description of Work","Estimated hrs","Actual hrs","Planned/Unplanned","Result","Comments")) %>%
  # delete the first row
  slice(-2) %>% 
  filter(!is.na(DATE)) %>% 
  mutate(employee="Alene Onion") %>% 
  mutate(week=((yday(DATE)-5)/7),
         week=as.integer(week)) %>% 
  distinct() 

woodfield<-read_excel("C:/Users/amonion.000/New York State Office of Information Technology Services/LMAS - General/telecommuting_journal_kw.xls",sheet="Completed",col_types = c("date", "text","text", "numeric", "numeric","text","text","text"))
woodfield<-as.data.frame(woodfield)
woodfield<-woodfield %>%
  # rename with first row
  set_names(c("DATE","Description of Work","Project","Estimated hrs","Actual hrs","Planned/Unplanned","Result","Comments")) %>%
  # delete the first row
  slice(-2) %>% 
  filter(!is.na(DATE)) %>% 
  mutate(employee="Karen Woodfield") %>% 
  mutate(week=((yday(DATE)-5)/7),
         week=as.integer(week)) %>% 
  distinct() 

matt<-read_excel("C:/Users/amonion.000/New York State Office of Information Technology Services/LMAS - General/telecommuting_journal_MK.xlsx",sheet="Work Journal",col_types = c("date", "text", "text","numeric", "numeric","text","text","text"))
matt<-as.data.frame(matt)
matt<-matt %>%
  # rename with first row
  set_names(c("DATE","Description of Work","Project","Estimated hrs","Actual hrs","Planned/Unplanned","Result","Comments")) %>%
  # delete the first row
  slice(-2) %>% 
  filter(!is.na(DATE)) %>% 
  mutate(employee="Matt Kraft") %>% 
  mutate(week=((yday(DATE)-5)/7),
         week=as.integer(week)) %>% 
  distinct() 

rebecca<-read_excel("C:/Users/amonion.000/New York State Office of Information Technology Services/LMAS - General/telecommuting_journal_RMG.xls",sheet="Completed",col_types = c("date", "text","text", "numeric", "numeric","text","text","text","text","text","text","text","text","text"))
rebecca<-as.data.frame(rebecca)
rebecca<-rebecca %>%
  # rename with first row
  set_names(c("DATE","Project","Description of Work","Estimated hrs","Actual hrs","Planned/Unplanned","Comments","Result","junk1","junk2","junk3","junk4","junk5","junk6")) %>%
  # delete the first row
  slice(-2) %>% 
  filter(!is.na(DATE)) %>% 
  select(DATE,Project,`Description of Work`,`Estimated hrs`,`Actual hrs`,`Planned/Unplanned`,Result,Comments) %>%
  mutate(employee="Rebecca Gorney") %>% 
  mutate(week=((yday(DATE)-5)/7),
         week=as.integer(week)) %>% 
  distinct() 

stephanie<-read_excel("C:/Users/amonion.000/New York State Office of Information Technology Services/LMAS - General/telecommuting_journal_sgj.xls",sheet="Work Journal",col_types = c("date","text", "text", "numeric", "numeric","text","text","text","text","text","text"))
stephanie<-as.data.frame(stephanie)
stephanie<-stephanie %>%
  # rename with first row
  set_names(c("DATE","Description of Work","Project","Estimated hrs","Actual hrs","Planned/Unplanned","Result","Comments",
              "junk","junk1","junk2")) %>%
  # delete the first row
  slice(-2) %>% 
  filter(!is.na(DATE)) %>% 
  mutate(employee="Stephanie June") %>% 
  mutate(week=((yday(DATE)-5)/7),
         week=as.integer(week)) %>% 
  distinct() 

jesse<-read_excel("C:/Users/amonion.000/New York State Office of Information Technology Services/LMAS - General/JSK telecommuting_journal_V2.xlsx",sheet="Completed",col_types = c("date", "text", "numeric", "numeric","text","text","text","text"))
jesse<-as.data.frame(jesse)
jesse<-jesse %>%
  # rename with first row
  set_names(c("DATE","Description of Work","Estimated hrs","Actual hrs","Project",
              "Planned/Unplanned","Result","Comments")) %>%
  # delete the first row
  slice(-2) %>% 
  filter(!is.na(DATE)) %>% 
  mutate(employee="Jesse Keltz") %>% 
  mutate(week=((yday(DATE)-5)/7),
         week=as.integer(week)) %>% 
  distinct() 

#merge together:
FlagMerge<-function(x, y){
  df<- merge(x, y, all= TRUE)
  return(df)
}
hrs<- Reduce(FlagMerge, list(alene, woodfield,jesse, matt,rebecca,stephanie))
hrs<-hrs %>% 
  select(week,DATE,employee,Project,`Description of Work`,`Estimated hrs`,`Actual hrs`,`Planned/Unplanned`,Result,Comments) %>% 
  mutate(DATE=as.Date(DATE)) %>% 
  arrange(DATE,employee) %>% 
  distinct()
rm(list=c('alene','woodfield','jesse','karen','matt','stephanie','rebecca','FlagMerge'))

datatable(hrs, extensions = 'Buttons', options = list(dom = 'Bfrtip',buttons = c('copy', 'csv', 'excel', 'pdf', 'print')))
```

##Combined Plot {.tabset}
Plot of all the hours spent by LMAS staff on individual projects
```{r, echo=FALSE, results='asis', message=FALSE, warning=FALSE}
combined<-hrs %>% 
  mutate(Project=toupper(Project),
         week=as.character(week)) %>% 
  rename(hours=`Actual hrs`) %>% 
  mutate(hours=ifelse(is.na(hours),0,hours)) %>% 
  select(week,Project,hours) %>% 
  group_by(week,Project) %>% 
  summarise(hours=sum(hours)) %>% 
  ungroup()

print(ggplot(data=combined, aes(x=Project, y=hours, fill=week)) +
  geom_bar(stat="identity", color="black", position=position_dodge())+
  theme_minimal()+
  scale_fill_brewer(palette="Set2") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
  coord_flip())
```

##Individual Plots {.tabset}
Plot of all the hours spent by specified LMAS staff on individual projects
```{r, echo=FALSE, results='asis', message=FALSE, warning=FALSE}
hrs<-hrs %>% 
  arrange(employee)
params<-unique(hrs$employee)
nparams<-length(params)

for(j in 1:nparams){
  display<-paste("  \n \n","###",params[j],"  \n",sep="")
      cat(display)
      rm(display)
employee<-hrs %>% 
  filter(employee==params[j]) %>% 
  mutate(Project=toupper(Project),
         week=as.character(week)) %>% 
  rename(hours=`Actual hrs`) %>% 
  mutate(hours=ifelse(is.na(hours),0,hours)) %>% 
  select(week,Project,hours) %>% 
  group_by(week,Project) %>% 
  summarise(hours=sum(hours)) %>% 
  ungroup()

print(ggplot(data=employee, aes(x=Project, y=hours, fill=week)) +
  geom_bar(stat="identity", color="black", position=position_dodge())+
  theme_minimal()+
  scale_fill_brewer(palette="Set2") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
  coord_flip())
}
```